server:
  port: 8082
spring:
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  application:
    name: account-micro-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seata_account?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: cedric
    password: haos123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.cn.entity
  configuration:
    map-underscore-to-camel-case: true
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8781/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000