server:
  port: 8283
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8781/eureka/
spring:
  application:
    name: config-micro-server
  cloud:
    config:
      server:
        git:
          uri: